apiVersion: apps/v1
kind: Deployment
metadata:
  name: eso-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eso-k8s-app
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: eso-k8s-app
    spec:
      containers:
        - name: eso-k8s-app
          image: eso-k8s-integration-demo-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: eso-k8s-app-service
spec:
  selector:
    app: eso-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
