apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store-test
    kind: SecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: DUMMY_ESO_TEST_SECRET
