apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store-test
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-sm-secret
            key: secret-access-key
